#pragma once

#include <unordered_map>
#include <string>

// Only common names are included
// otherwise this file would be at least 200MB long (there are 1085 classes)
// let that sink in while doing anything here
namespace NightMTA::Shared::Windows::COM {
    using COMServiceEntry = std::vector<std::string>;

    namespace COMEntries {
        inline const COMServiceEntry Win32_BIOS {
            "BiosCharacteristics",
            "BIOSVersion",
            "BuildNumber",
            "Caption",
            "CodeSet",
            "CurrentLanguage",
            "Description",
            "EmbeddedControllerMajorVersion",
            "EmbeddedControllerMinorVersion",
            "IdentificationCode",
            "InstallableLanguages",
            "InstallDate",
            "LanguageEdition",
            "ListOfLanguages",
            "Manufacturer",
            "Name",
            "OtherTargetOS",
            "PrimaryBIOS",
            "ReleaseDate",
            "SerialNumber",
            "SMBIOSBIOSVersion",
            "SMBIOSMajorVersion",
            "SMBIOSMinorVersion",
            "SMBIOSPresent",
            "SoftwareElementID",
            "SoftwareElementState",
            "Status",
            "SystemBiosMajorVersion",
            "SystemBiosMinorVersion",
            "TargetOperatingSystem",
            "Version",
        };
        inline const COMServiceEntry Win32_Environment {
            "Caption",
            "Description",
            "InstallDate",
            "Name",
            "Status",
            "SystemVariable",
            "UserName",
            "VariableValue",
        };
        inline const COMServiceEntry Win32_MotherboardDevice {
            "Name",
            "DeviceID",
            "Availability",
            "SecondaryBusType",
            "PrimaryBusType",
            "Caption",
            "CreationClassName",
            "Description",
            "Status",
            "SystemCreationClassName",
            "SystemName",
        };
        inline const COMServiceEntry Win32_OperatingSystem {
            "BootDevice",
            "BuildNumber",
            "BuildType",
            "Caption",
            "CodeSet",
            "CountryCode",
            "CreationClassName",
            "CSCreationClassName",
            "CSDVersion",
            "CSName",
            "CurrentTimeZone",
            "DataExecutionPrevention_32BitApplications",
            "DataExecutionPrevention_Available",
            "DataExecutionPrevention_Drivers",
            "DataExecutionPrevention_SupportPolicy",
            "Debug",
            "Description",
            "Distributed",
            "EncryptionLevel",
            "ForegroundApplicationBoost",
            "FreePhysicalMemory",
            "FreeSpaceInPagingFiles",
            "FreeVirtualMemory",
            "InstallDate",
            "LargeSystemCache",
            "LastBootUpTime",
            "LocalDateTime",
            "Locale",
            "Manufacturer",
            "MaxNumberOfProcesses",
            "MaxProcessMemorySize",
            "MUILanguages",
            "Name",
            "NumberOfLicensedUsers",
            "NumberOfProcesses",
            "NumberOfUsers",
            "OperatingSystemSKU",
            "Organization",
            "OSArchitecture",
            "OSLanguage",
            "OSProductSuite",
            "OSType",
            "OtherTypeDescription",
            "PAEEnabled",
            "PlusProductID",
            "PlusVersionNumber",
            "PortableOperatingSystem",
            "Primary",
            "ProductType",
            "RegisteredUser",
            "SerialNumber",
            "ServicePackMajorVersion",
            "ServicePackMinorVersion",
            "SizeStoredInPagingFiles",
            "Status",
            "SuiteMask",
            "SystemDevice",
            "SystemDirectory",
            "SystemDrive",
            "TotalSwapSpaceSize",
            "TotalVirtualMemorySize",
            "TotalVisibleMemorySize",
            "Version",
            "WindowsDirectory",
        };
        inline const COMServiceEntry Win32_PhysicalMemory {
            "Attributes",
            "BankLabel",
            "Capacity",
            "Caption",
            "ConfiguredClockSpeed",
            "ConfiguredVoltage",
            "CreationClassName",
            "DataWidth",
            "Description",
            "DeviceLocator",
            "FormFactor",
            "HotSwappable",
            "InstallDate",
            "InterleaveDataDepth",
            "InterleavePosition",
            "Manufacturer",
            "MaxVoltage",
            "MemoryType",
            "MinVoltage",
            "Model",
            "Name",
            "OtherIdentifyingInfo",
            "PartNumber",
            "PositionInRow",
            "PoweredOn",
            "Removable",
            "Replaceable",
            "SerialNumber",
            "SKU",
            "SMBIOSMemoryType",
            "Speed",
            "Status",
            "Tag",
            "TotalWidth",
            "TypeDetail",
            "Version",
        };
        inline const COMServiceEntry Win32_Processor {
            "AddressWidth",
            "Architecture",
            "AssetTag",
            "Availability",
            "Caption",
            "Characteristics",
            "ConfigManagerErrorCode",
            "ConfigManagerUserConfig",
            "CpuStatus",
            "CreationClassName",
            "CurrentClockSpeed",
            "CurrentVoltage",
            "DataWidth",
            "Description",
            "DeviceID",
            "ErrorCleared",
            "ErrorDescription",
            "ExtClock",
            "Family",
            "InstallDate",
            "L2CacheSize",
            "L2CacheSpeed",
            "L3CacheSize",
            "L3CacheSpeed",
            "LastErrorCode",
            "Level",
            "LoadPercentage",
            "Manufacturer",
            "MaxClockSpeed",
            "Name",
            "NumberOfCores",
            "NumberOfEnabledCore",
            "NumberOfLogicalProcessors",
            "OtherFamilyDescription",
            "PartNumber",
            "PNPDeviceID",
            "PowerManagementCapabilities",
            "PowerManagementSupported",
            "ProcessorId",
            "ProcessorType",
            "Revision",
            "Role",
            "SecondLevelAddressTranslationExtensions",
            "SerialNumber",
            "SocketDesignation",
            "Status",
            "StatusInfo",
            "Stepping",
            "SystemCreationClassName",
            "SystemName",
            "ThreadCount",
            "UniqueId",
            "UpgradeMethod",
            "Version",
            "VirtualizationFirmwareEnabled",
            "VMMonitorModeExtensions",
            "VoltageCaps",
        };
    }

    inline const std::unordered_map<std::string, COMServiceEntry> COMServiceMap = {
        {"Win32_BIOS", COMEntries::Win32_BIOS},
        {"Win32_Environment", COMEntries::Win32_Environment},
        {"Win32_MotherboardDevice", COMEntries::Win32_MotherboardDevice},
        {"Win32_OperatingSystem", COMEntries::Win32_OperatingSystem},
        {"Win32_PhysicalMemory", COMEntries::Win32_PhysicalMemory},
        {"Win32_Processor", COMEntries::Win32_Processor},
    };
}
